#!/bin/sh

if [ x"${SKIP_TEST_INTEGRATION_GENERATION}" != "x" ]; then
	echo "Skipping the build of the tests..."
	exit 0;
fi

echo "Building the test artifacts..."
./dev/tests/integration_ios_build.sh
./dev/tests/integration_android_build.sh
./dev/tests/integration_update_artifact_latest_build.sh

echo "Syncing the test artifacts with the remote..."
./dev/tests/test_remote_sync.sh push

git update-index --add dev/tests/artifact_files_latest_build.info

echo "Done."
