// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASeSSpV31yRNKGq2Tdv2CY2_1z8jCkFgk',
    appId: '1:781868708787:android:8eb3bbfd5c1e930b5f11c6',
    messagingSenderId: '781868708787',
    projectId: 'gmadrid-natacion-f5fcd',
    storageBucket: 'gmadrid-natacion-f5fcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxfj_pecHuskRV960HitQ3JyALywmaRRs',
    appId: '1:781868708787:ios:861a5742b6168d865f11c6',
    messagingSenderId: '781868708787',
    projectId: 'gmadrid-natacion-f5fcd',
    storageBucket: 'gmadrid-natacion-f5fcd.appspot.com',
    iosClientId: '781868708787-j1u5b9ivrqvco884aob1p2dh9lqiu34h.apps.googleusercontent.com',
    iosBundleId: 'net.bertamini.gmadrid.natacion.gmadridNatacion',
  );
}
