-keep class pl.leancode.patrol.** { *; }
-keep class kotlin.reflect.jvm.internal.impl.builtins.PrimitiveType { *; }
-keep class org.junit.runners.** { *; }
-keep class androidx.window.sidecar.** { *; }
-keep class io.flutter.embedding.** { *; }