name: Integration tests
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
jobs:
  integration-tests-ios:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - name: Run Flutter Pub Get
        run: flutter pub get
      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
      - name: Install Patrol cli
        run: 'dart pub global activate patrol_cli'
      - name: Run Android Integration tests
        run: './integration_android_run.sh'
